### PR TITLE
I think using 'current' version of gvm's groovysh is more flexible

### PR DESCRIPTION
**Pull request by lwiechec**
As my version is 2.4.0, I had trouble starting malabar-mode. With this change, the 'current' version is used that saves the trouble for the user to redefine it.

### CODE REVIEW

**Comment by m0smith** [comment]
Which OS and EMACS version are you using.  I have tried this on Windows and it did not work.  I like the idea and will get it working with Windows as well.

**Comment by lwiechec** [comment]
Hi, I'm using Emacs 24.4.1 on Linux Pepperming Five (a clone of Ubuntu).
It will probably not work in Windows as 'current' is a symbolic link and Windows does not support it.

Sorry, I tend to forget that this package should also run well on Windows... :)

**Comment by lwiechec** [comment]
I have thought about this change because, when trying to run it for the first time (and knowing very little about gvm and groovy), the `run-malabar-groovy` just didn't work. 
To make it more friendly to the user, there could be also additional check if the defined value of `malabar-groovy-grooysh` exists; otherwise a meaningful error message should be displayed...

**Comment by m0smith** [comment]
That is a good idea.  I'll add that.

**Pull request merged**
